CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "mail" varchar UNIQUE NOT NULL
);

CREATE TABLE "playlists" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "link" varchar NOT NULL,
  "like_count" int NOT NULL DEFAULT 0, 
  "description" varchar NOT NULL
);

CREATE TABLE "liked_playlist" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "playlist_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  CONSTRAINT unique_playlist_user_pair UNIQUE ("playlist_id", "user_id")
);

CREATE TABLE "follows" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "follower_id" int NOT NULL,
  "follows_id" int NOT NULL
);

ALTER TABLE "playlists" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "liked_playlist" ADD FOREIGN KEY ("playlist_id") REFERENCES "playlists" ("id");

ALTER TABLE "liked_playlist" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "follows" ADD FOREIGN KEY ("follower_id") REFERENCES "users" ("id");

ALTER TABLE "follows" ADD FOREIGN KEY ("follows_id") REFERENCES "users" ("id");
