// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: follows.sql

package db

import (
	"context"
)

const addFollow = `-- name: AddFollow :exec
INSERT INTO follows (follower_id, follows_id) VALUES ($1, $2)
`

type AddFollowParams struct {
	FollowerID int32 `json:"follower_id"`
	FollowsID  int32 `json:"follows_id"`
}

func (q *Queries) AddFollow(ctx context.Context, arg AddFollowParams) error {
	_, err := q.db.ExecContext(ctx, addFollow, arg.FollowerID, arg.FollowsID)
	return err
}

const removeFollow = `-- name: RemoveFollow :exec
DELETE FROM follows WHERE follower_id = $1 AND follows_id = $2
`

type RemoveFollowParams struct {
	FollowerID int32 `json:"follower_id"`
	FollowsID  int32 `json:"follows_id"`
}

func (q *Queries) RemoveFollow(ctx context.Context, arg RemoveFollowParams) error {
	_, err := q.db.ExecContext(ctx, removeFollow, arg.FollowerID, arg.FollowsID)
	return err
}
