// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Follow struct {
	ID         int32 `json:"id"`
	FollowerID int32 `json:"follower_id"`
	FollowsID  int32 `json:"follows_id"`
}

type LikedPlaylist struct {
	ID         int32 `json:"id"`
	PlaylistID int32 `json:"playlist_id"`
	UserID     int32 `json:"user_id"`
}

type Playlist struct {
	ID          int32     `json:"id"`
	UserID      int32     `json:"user_id"`
	CreatedAt   time.Time `json:"created_at"`
	Link        string    `json:"link"`
	LikeCount   int32     `json:"like_count"`
	Description string    `json:"description"`
}

type User struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	Mail      string    `json:"mail"`
}
