// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	AddFollow(ctx context.Context, arg AddFollowParams) error
	AddUserLike(ctx context.Context, arg AddUserLikeParams) (LikedPlaylist, error)
	CountLikesForPlaylist(ctx context.Context, playlistID int32) (int64, error)
	CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePlaylist(ctx context.Context, id int32) error
	DeleteUserLike(ctx context.Context, id int32) error
	GetLikedPlaylistsByUser(ctx context.Context, userID int32) ([]Playlist, error)
	GetPlaylistsByUserID(ctx context.Context, userID int32) ([]Playlist, error)
	GetUser(ctx context.Context, username string) (User, error)
	LikePlaylist(ctx context.Context, id int32) (Playlist, error)
	RemoveFollow(ctx context.Context, arg RemoveFollowParams) error
	UnlikePlaylist(ctx context.Context, id int32) (Playlist, error)
}

var _ Querier = (*Queries)(nil)
